import dayjs from 'dayjs'
import utc from 'dayjs/plugin/utc'

dayjs.extend(utc)

const DEFAULT_TIMEZONE = '-0700'

const setTime = (date, time, tz = DEFAULT_TIMEZONE) => {
  const str = tz.replace(/[^-0-9]/g, '') || '0'
  const offset = Number.parseInt(str) / 100
  return dayjs(`${date} ${time.replace(/MST$/, DEFAULT_TIMEZONE)}`, 'MM/DD/YYYY HH:mm:ssZZ').utcOffset(offset)
}

export const getDates = (businessHours = [], duration = 30, tz) => {
  return businessHours
    .map(hr => {
      const date = dayjs(hr.date, 'MM/DD/YYYY')
      const times = []

      const close = setTime(hr.date, hr.endTime, tz)
      let next = setTime(hr.date, hr.startTime, tz)

      while (next.valueOf() < close.valueOf()) {
        const value = next.format('hh:mm A')
        times.push({ value, label: value })
        next = next.add(duration, 'minute')
      }

      return {
        value: date.toDate(),
        label: date.format('MMM DD - dddd'),
        times,
      }
    })
    .reduce((acc, next) => {
      const found = acc.find(a => a.value.valueOf() === next.value.valueOf())

      if (found && next.times.length > 0) {
        found.times = [...found.times, ...next.times]
      } else if (next.times.length > 0) {
        return [...acc, next]
      }

      return acc
    }, [])
}

// Generate unique IDs for use as pseudo-private/protected names.
// Similar in concept to
// <http://wiki.ecmascript.org/doku.php?id=strawman:names>.
//
// The goals of this function are twofold:
//
// * Provide a way to generate a string guaranteed to be unique when compared
//   to other strings generated by this function.
// * Make the string complex enough that it is highly unlikely to be
//   accidentally duplicated by hand (this is key if you're using `ID`
//   as a private/protected name on an object).
//
// Use:
//
//     const privateName = ID()
//     const o = { 'public': 'foo' }
//     o[privateName] = 'bar'
export const ID = () => {
  // Math.random should be unique because of its seeding algorithm.
  // Convert it to base 36 (numbers + letters), and grab the first 9 characters
  // after the decimal.
  return '_' + Math.random().toString(36).substr(2, 9)
}
